### ISSUE TITLE
Post-update hook for openrgb.nvim ... Exit status: 127

### ISSUE THREAD

**Issue by dob9601** [antoinemadec/openrgb.nvim#1]
When trying to install this plugin using vim-plug, I get the error:
```
Post-update hook for openrgb.nvim ... Exit status: 127
```
The plugin still installs, but no commands are registered and reloading vim yields the error:
```
Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: OpenRGBSync
```
on startup

**Comment by antoinemadec** [comment]
Did you call this command after installing the plugin ```:UpdateRemotePlugins``` ?

**Comment by dob9601** [comment]
Worked! Assumed that `{'do': 'UpdateRemotePlugins'}` was supposed to call that for me

**Comment by antoinemadec** [comment]
Dopeness ! Dont hesitate if you have any feedback or PR you wanna push.
