### ISSUE TITLE
How to integrate with galaxyline.nvim

### ISSUE THREAD

**Issue by ecosse3** [antoinemadec/openrgb.nvim#2]
Hey,

do you have any idea how I can integrate this plugin with galaxyline nvim? Overall openrgb works and it sets custom colors to my keyboard, but changes lights between specific vim modes doesn't work.

Any ideas?

**Comment by antoinemadec** [comment]
@ecosse3 , you have to call this function whenever galaxyline updates its status:
```vim
function OpenRGBStatuslineFunc()
  if g:openrgb_is_ready
    call OpenRGBChangeColorFromMode(mode())
  endif
  return ''
endfunction
```

I don't know how glaxyline.nvim works, maybe the best option is to open a ticket in there repo?

Otherwise, you can try an approach with a timer:
```vim
let g:current_mode = ''
function! s:ModeCheck(id)
    let new_mode = mode()
    if new_mode != g:current_mode
        call OpenRGBStatuslineFunc()
        let g:current_mode = new_mode
    endif
endfunction
call timer_start(100, function('s:ModeCheck'), {'repeat': -1})
```

**Comment by antoinemadec** [comment]
Please note that when this will be merged into neovim https://github.com/vim/vim/commit/f1e8876fa2359b572d262772747405d3616db670 we won't need to rely on the statusline or timer trick.

**Comment by ecosse3** [comment]
Thank you! The second option is working for now. I will try to make it work with galaxyline in lua itself or open an issue there. Thanks!
